client_id: 3MVG9A2kN3Bn17ht5cv.XwHeIGcHac8dPKfImO2k_BqDL8qEETzvvwhnRrT9hpEiYJVkvUAwehoW2sD4Kmxcy
client_secret: 7046106733378379458
username: arturo.diaz@wavesoluciones.com
password: 91arturo148U6BX88waLQuy341sQqrTtrQya
debugging: true

