client_id: 3MVG9A2kN3Bn17huVI7AAsia9nFDuWYTZ1biOtTB6k7.AY5Af4p5OtTPchZhUF8CyZ2ktmMf2qZL3_.x67lFo
client_secret: 3236372913056006794
username: arturo.diaz1@wavesoluciones.com
password: 91arturo148U8bMEw4Du1IMbqt3PCZgnFu8
debugging: true

